create table IntegrationContent (
  id bigint generated by default as identity,
  lastUpdated timestamp
);

insert into IntegrationContent (id, lastUpdated) values
  (1, '2010-01-01-00.00.00.000000'),
  (2, '2010-01-01-00.00.00.000000'),
  (3, '2010-01-01-00.00.00.000000');

create table BulkAndFullChangesetTestProfile (
  name varchar(20) not null unique,
  lastRun timestamp
);
insert into BulkAndFullChangesetTestProfile (name, lastRun) values
  ('test', NULL);

create table IntegrationDeleted (
  id bigint primary key,
  lastUpdated timestamp
);
insert into IntegrationDeleted (id, lastUpdated) values
  (4, '2010-01-01-00.00.00.000000'),
  (5, '2010-01-01-00.00.00.000000');

