create table feed_provider_data (
  id bigint generated by default as identity,
  lastUpdated timestamp,
  provider varchar(255),
  kind varchar(255),
  value varchar(255)
);

insert into feed_provider_data (id, lastUpdated, provider, kind, value) values
  (1, '2010-01-01-00.00.00.000000', null, null, 'val1'),
  (2, '2010-01-01-00.00.00.000000', 'p1', 'k1', 'val2'),
  (3, '2010-01-01-00.00.00.000000', 'p2', 'k2', 'val3'),
  (4, '2010-01-01-00.00.00.000000', '', '', 'val4');


create table feed_provider_deleted (
  id bigint primary key,
  lastUpdated timestamp,
  provider varchar(255),
  kind varchar(255)
);
insert into feed_provider_deleted (id, lastUpdated, provider, kind) values
  (5, '2010-01-01-00.00.00.000000', 'p1', 'k1'),
  (6, '2010-01-01-00.00.00.000000', null, null);


