create table IntegrationContent (
  id bigint generated by default as identity,
  lastUpdated timestamp
);

insert into IntegrationContent (id, lastUpdated) values
  (1, '2010-01-01-00.00.00.000000'),
  (2, '2010-01-01-00.00.00.000000'),
  (3, '2010-01-01-00.00.00.000000');

create table IntegrationProfile (
  name varchar(20) not null unique,
  lastRun timestamp
);
insert into IntegrationProfile (name, lastRun) values
  ('test', NULL);

create table IntegrationDeleted (
  id bigint primary key,
  lastUpdated timestamp
);
insert into IntegrationDeleted (id, lastUpdated) values
  (4, '2010-01-01-00.00.00.000000'),
  (5, '2010-01-01-00.00.00.000000');

  create table IntegrationTextContent (
  id bigint generated by default as identity,
  text_content clob
);

insert into IntegrationTextContent (id, text_content) values
  (1, 'Hello & < > " '' goodbye');

create procedure IntegrationContentSP(startTime timestamp, endTime timestamp)
parameter style java
language java
reads sql data
dynamic result sets 1
external name 'com.t11e.discovery.datatool.IntegrationTestBase.integrationContentSP';
