create table empty_table (
  id bigint generated by default as identity,
  foo varchar(255),
  bar varchar(255),
  json_column clob,
  last_updated timestamp
);

create table date_range_test (
  id bigint generated by default as identity,
  last_updated timestamp
);

insert into date_range_test (last_updated) values ('2010-02-01-00.00.00.000000');
insert into date_range_test (last_updated) values ('2010-02-01-00.00.01.000000');
insert into date_range_test (last_updated) values ('2010-02-01-00.00.03.000000');
