create table IntegrationContent (
  id bigint generated by default as identity,
  lastUpdated timestamp
);

insert into IntegrationContent (lastUpdated) values
  ('2010-01-01-00.00.00.000000'),
  ('2010-01-01-00.00.00.000000'),
  ('2010-01-01-00.00.00.000000');

create table IntegrationProfile (
  name varchar(20) not null,
  lastRun timestamp
);
insert into IntegrationProfile (name, lastRun) values
  ('test', NULL);
