create table Content (
  id bigint generated by default as identity,
  name varchar(255),
  json clob);

insert into Content (id, name, json) values
  (1, 'joe', '{"name":"joseph","age":21}'),
  (2, 'bob', '{"name":"robert","age":22}'),
  (3, 'aaron', '{"name":"jack","age":23}');
